import { describe, expect, it } from 'vitest'
import { createHash } from 'node:crypto'
import { readFileSync, rmSync } from 'node:fs'
import { join } from 'node:path'
import assets from '../../src/shared/terminal-raster-codec-assets.json'
import { describeProcessFailure, runProcessSync } from './script-child-process.mjs'
import { createPatchTestDirectory, writePatchTestTree } from './xterm-patch-test-files.mjs'

describe('terminal raster asset checkout bytes', () => {
  it.each([true, false])(
    'checks generated bytes with the LF asset policy enabled=%s',
    async (enabled) => {
      const directory = await createPatchTestDirectory()
      const filename = 'src/shared/terminal-raster-codec-assets.json'
      const content = `${JSON.stringify(assets, null, 2)}\n`
      await writePatchTestTree(directory, {
        '.gitattributes': enabled ? readFileSync('.gitattributes', 'utf8') : '',
        [filename]: content
      })
      for (const args of [
        ['init', '--quiet'],
        ['add', '--', '.gitattributes', filename],
        ['checkout-index', '--force', '--all']
      ]) {
        if (args[0] === 'checkout-index') {
          rmSync(join(directory, filename))
        }
        const result = runProcessSync({
          program: 'git',
          args: ['-c', 'core.autocrlf=true', '-c', 'core.eol=crlf', ...args],
          cwd: directory,
          env: { ...process.env, ORCA_BACKGROUND_LAUNCH: '1' },
          timeoutMs: 30_000
        })
        expect(result.code, describeProcessFailure(result)).toBe(0)
      }
      const actual = readFileSync(join(directory, filename), 'utf8')
      expect(actual.includes('\r\n')).toBe(!enabled)
      expect(createHash('sha256').update(actual.replaceAll('\r\n', '\n')).digest('hex')).toBe(
        createHash('sha256').update(content).digest('hex')
      )
    }
  )
})
