// The main `claude` command's options and how its parser takes their values, from the option
// table of claude 2.1.280: `<v>` is a value, `[v]` an optional one, `<v...>` several.

export type ClaudeCliOptionArity = 'switch' | 'value' | 'optional' | 'variadic'

export const CLAUDE_CLI_OPTIONS: Readonly<Record<string, ClaudeCliOptionArity>> = {
  '--add-dir': 'variadic',
  '--advisor': 'value',
  '--agent': 'value',
  '--agent-color': 'value',
  '--agent-id': 'value',
  '--agent-name': 'value',
  '--agent-type': 'value',
  '--agents': 'value',
  '--allow-dangerously-skip-permissions': 'switch',
  '--allowed-tools': 'variadic',
  '--allowedTools': 'variadic',
  '--append-subagent-system-prompt': 'value',
  '--append-subagent-system-prompt-file': 'value',
  '--append-system-prompt': 'value',
  '--append-system-prompt-file': 'value',
  '--attach-serve': 'value',
  '--autocompact': 'value',
  '--await-initialize': 'switch',
  '--ax-screen-reader': 'switch',
  '--background': 'switch',
  '--bare': 'switch',
  '--betas': 'variadic',
  '--bg': 'switch',
  '--brief': 'switch',
  '--channels': 'variadic',
  '--chrome': 'switch',
  '--cloud': 'optional',
  '--continue': 'switch',
  '--correlation-id': 'value',
  '--dangerously-load-development-channels': 'variadic',
  '--dangerously-skip-permissions': 'switch',
  '--debug': 'optional',
  '--debug-file': 'value',
  '--debug-to-stderr': 'switch',
  '--deep-link-cwd-b64': 'value',
  '--deep-link-last-fetch': 'value',
  '--deep-link-origin': 'switch',
  '--deep-link-repo': 'value',
  '--disable-slash-commands': 'switch',
  '--disallowed-tools': 'variadic',
  '--disallowedTools': 'variadic',
  '--effort': 'value',
  '--enable-auth-status': 'switch',
  '--enable-auto-mode': 'switch',
  '--environment': 'value',
  '--exclude-dynamic-system-prompt-sections': 'switch',
  '--fallback-model': 'value',
  '--file': 'variadic',
  '--fork-session': 'switch',
  '--forward-home-settings': 'value',
  '--forward-subagent-text': 'switch',
  '--from-pr': 'optional',
  '--help': 'switch',
  '--ide': 'switch',
  '--include-hook-events': 'switch',
  '--include-partial-messages': 'switch',
  '--inherit-permission-mode': 'value',
  '--init': 'switch',
  '--init-only': 'switch',
  '--input-format': 'value',
  '--json-schema': 'value',
  '--maintenance': 'switch',
  '--managed-settings': 'value',
  '--max-budget-usd': 'value',
  '--max-thinking-tokens': 'value',
  '--max-turns': 'value',
  '--mcp-config': 'variadic',
  '--messaging-socket-path': 'value',
  '--model': 'value',
  '--name': 'value',
  '--no-chrome': 'switch',
  '--no-session-persistence': 'switch',
  '--on-branch': 'value',
  '--output-format': 'value',
  '--parent-session-id': 'value',
  '--permission-mode': 'value',
  '--permission-prompt-tool': 'value',
  '--permission-prompts': 'value',
  '--plan-mode-instructions': 'value',
  '--plan-mode-required': 'switch',
  '--plugin-dir': 'value',
  '--plugin-dir-no-mcp': 'value',
  '--plugin-url': 'value',
  '--pool': 'value',
  '--prefill': 'value',
  '--prefill-b64': 'value',
  '--print': 'switch',
  '--project-config-root': 'value',
  '--prompt-suggestions': 'optional',
  '--rc': 'optional',
  '--ref': 'value',
  '--remote': 'optional',
  '--remote-control': 'optional',
  '--remote-control-session-name-prefix': 'value',
  '--replay-user-messages': 'switch',
  '--reply-on-resume': 'switch',
  '--restricted': 'switch',
  '--resume': 'optional',
  '--resume-drops-turn': 'value',
  '--resume-session-at': 'value',
  '--rewind-files': 'value',
  '--safe-mode': 'switch',
  '--sdk-url': 'value',
  '--session-id': 'value',
  '--session-mirror': 'switch',
  '--setting-sources': 'value',
  '--settings': 'value',
  '--strict-mcp-config': 'switch',
  '--system-prompt': 'value',
  '--system-prompt-file': 'value',
  '--system-prompt-snapshot': 'value',
  '--task-budget': 'value',
  '--team-name': 'value',
  '--teammate-mode': 'value',
  '--teleport': 'optional',
  '--thinking': 'value',
  '--thinking-display': 'value',
  '--tmux': 'switch',
  '--tools': 'variadic',
  '--verbose': 'switch',
  '--version': 'switch',
  '--watch-artifact': 'value',
  '--watch-artifact-no-autoreact': 'value',
  '--workload': 'value',
  '--worktree': 'optional'
}

/** Short spellings, by their long name. */
export const CLAUDE_CLI_SHORT_OPTIONS: Readonly<Record<string, string>> = {
  '-c': '--continue',
  '-d': '--debug',
  '-d2e': '--debug-to-stderr',
  '-h': '--help',
  '-n': '--name',
  '-p': '--print',
  '-r': '--resume',
  '-v': '--version',
  '-w': '--worktree'
}

/** Options whose value is required, so the parser takes the next token even if it starts with
 *  `-`. */
export const CLAUDE_CLI_REQUIRED_VALUE_OPTIONS: readonly string[] = [
  ...Object.keys(CLAUDE_CLI_OPTIONS),
  ...Object.keys(CLAUDE_CLI_SHORT_OPTIONS)
].filter((option) => {
  const arity = CLAUDE_CLI_OPTIONS[CLAUDE_CLI_SHORT_OPTIONS[option] ?? option]
  return arity === 'value' || arity === 'variadic'
})
